### ISSUE TITLE
TypeError: setTimeout(...).unref is not a function

### ISSUE THREAD

**Issue by akaRem** [hunterloftis/stoppable#12]
Hi!
I have some problems with using stoppable on node v8.7.0

here are couple of stack traces:

```
    TypeError: setTimeout(...).unref is not a function

      at Immediate.setImmediate [as _onImmediate] (node_modules/stoppable/lib/stoppable.js:33:39)
      at runCallback (timers.js:785:20)
      at tryOnImmediate (timers.js:747:5)
      at processImmediate [as _immediateCallback] (timers.js:718:5)
```
```
    TypeError: setTimeout(...).unref is not a function

      at Immediate.setImmediate [as _onImmediate] (node_modules/stoppable/lib/stoppable.js:33:39)
      at runCallback (timers.js:785:20)
      at tryOnImmediate (timers.js:747:5)
      at processImmediate (timers.js:718:5)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
I use babel, jest, flow and lots of other things, so it's hard to say is it problem of stoppable or not.

**Comment by thyb** [comment]
https://github.com/hunterloftis/stoppable/blob/028df6a437db9c11fa0943a973af40a93897cc65/lib/stoppable.js#L33

I had to remove `.unref()` at the end of the line and it now works for me in Electron v1.8.2

**Comment by ronkorving** [comment]
That's very strange, `timer.unref()` has existed since before Node 0.10: https://nodejs.org/api/timers.html#timers_timeout_unref

**Comment by boneskull** [comment]
It'd be cool to see what the exact setup is here, but the problem isn't stoppable's.  stoppable could conceivably provide a workaround (e.g., using `require('timer').setTimeout()` instead), but I'd prefer not to make that change if it doesn't work.

@thyb 	If you're still encountering this, what happens when you restore `unref()` but instead change the line to `require('timer').setTimeout(destroyall, grace).unref()`?

**Comment by ronkorving** [comment]
I've seen things like this happen when run from Jest, which runs in Browser-mode by default, which means it replaces setTimeout and does not return an object with an `unref` function on it. Perhaps you're also running in some sort of browser emulation mode?

**Comment by glasser** [comment]
Could the call to `unref` be replaced by a call to `clearTimeout` in the `server.close` callback?

The point of `unref` is that it lets the Node process terminate if it's the only remaining thing. But that process isn't going to terminate until the server is closed (unless you've also unreffed the server, I guess?), so the first time it could possibly be relevant is after the `server.close` callback is done.  So we might as well just call clearTimeout ourselves at that point, no?

**Comment by tokiodeo** [comment]
replace `setTimeout` to `setImmediate`

**Comment by glasser** [comment]
fwiw we ended up forking and making a ton of improvements to this nice class, now at https://github.com/apollographql/apollo-server/blob/main/packages/server/src/plugin/drainHttpServer/stoppable.ts
- TypeScript rewrite
- `stop` is async instead of taking a callback
- no leaked timeout
- in fact we eventually changed it to not create a timeout at all and instead take an AbortController as an argument, which made it a lot easier to unit test (the caller does a timeout instead: https://github.com/apollographql/apollo-server/blob/f78240ef65bb9a0b610ef8b0cc6f142d86dbab13/packages/server/src/plugin/drainHttpServer/index.ts#L41-L51)
- it's an object rather than a closure to make it easier for white-box unit tests to look at internal state

**Comment by boneskull** [comment]
@glasser Care to publish that module standalone?

**Comment by glasser** [comment]
That hasn't been a priority for us --- I'd be happy to see somebody else copy it back from us and release and maintain it.
